#ifndef NOERRORS_H
#define NOERRORS_H
const int  ERROR_NONE    = 0;
const int  ERROR_RANGE_CHAR_NOT_VALID    = 1;
const int  ERROR_RANGE_LENGTH_NOT_VALID  = 2;
const int  ERROR_OPTION_NO_DIGITAL_ARGUMENT= 3;
const int  ERROR_LITTLE_LENGTH_PASSWORD = 4;
const int  ERROR_DICTONARY_EMPTY = 5;
const int  ERROR_EXT_MASK_NOT_VALID    = 6;
#endif // NOERRORS_H